title: Mushroom Showcase 
views:
  - !include views/light-view.yaml
  - !include views/cover-view.yaml
  - !include views/person-view.yaml
  - !include views/alarm-control-panel-view.yaml
  - !include views/fan-view.yaml
  - !include views/template-view.yaml
  - !include views/entity-view.yaml
  - !include views/chips-view.yaml
  - !include views/title-view.yaml
  - !include views/update-view.yaml
  - !include views/media-player-view.yaml
  - !include views/vacuum-view.yaml
  - !include views/lock-view.yaml
  - !include views/humidifier-view.yaml
  - !include views/select-view.yaml
  - !include views/number-view.yaml