input_number:
  percentage:
    name: Percentage
    initial: 30
    min: 0
    max: 100
    step: 0.5

template:
  - number: 
      - name: Percentage
        unique_id: percentage_number
        step: 0.5
        min: 0
        max: 100
        state: "{{ states('input_number.percentage') }}"
        set_value: 
          service: input_number.set_value
          target:
            entity_id: input_number.percentage
          data:
            value: "{{ value }}"

homeassistant:
  customize:
    input_number.percentage:
      friendly_name: Percentage Input Number
      unit_of_measurement: "%"
    number.percentage:
      friendly_name: Percentage Number
      unit_of_measurement: "%"